AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-user

  SAM Template for api-user

Globals:
  Function:
    Timeout: 3

# creating a dynamodb table 'users' with partition key = 'username'
Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  PersonalInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: personal_info
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  ContactInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: contact_info
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  EducationalInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: educational_info
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
      Handler: app.app
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref UserTable
        - DynamoDBCrudPolicy:
            TableName:
              !Ref PersonalInfoTable
        - DynamoDBCrudPolicy:
            TableName:
              !Ref ContactInfoTable
        - DynamoDBCrudPolicy:
            TableName:
              !Ref EducationalInfoTable
      Events:
        GetInformtaion:
          Type: Api
          Properties:
            Path: /info
            Method: get
        PutInformtaion:
          Type: Api
          Properties:
            Path: /info
            Method: put
        UserSignUp:
          Type: Api
          Properties:
            Path: /user
            Method: post